// Generated by scripts/build-widgets.mjs from messages/*.json. Do not edit.
export const YEAR_COPY = {
  "en": {
    "verdictRange": "In {city} you can synthesize vitamin D from {startMonth} to {endMonth}.",
    "verdictAllYear": "In {city} you can synthesize vitamin D all year round.",
    "verdictNever": "In {city} the sun never gets high enough to synthesize vitamin D."
  },
  "es": {
    "verdictRange": "En {city} puedes sintetizar vitamina D de {startMonth} a {endMonth}.",
    "verdictAllYear": "En {city} puedes sintetizar vitamina D durante todo el año.",
    "verdictNever": "En {city} el sol nunca alcanza la altura necesaria para sintetizar vitamina D."
  },
  "fr": {
    "verdictRange": "{atCityCap}, vous pouvez synthétiser la vitamine D {fromMonth} à {endMonth}.",
    "verdictAllYear": "{atCityCap}, vous pouvez synthétiser la vitamine D toute l'année.",
    "verdictNever": "{atCityCap}, le soleil n'atteint jamais la hauteur nécessaire pour synthétiser la vitamine D."
  },
  "de": {
    "verdictRange": "In {city} kannst du von {startMonth} bis {endMonth} Vitamin D bilden.",
    "verdictAllYear": "In {city} kannst du das ganze Jahr über Vitamin D bilden.",
    "verdictNever": "In {city} erreicht die Sonne nie die nötige Höhe, um Vitamin D zu bilden."
  },
  "ru": {
    "verdictRange": "{city}: витамин D можно синтезировать с {startMonth} по {endMonth}.",
    "verdictAllYear": "{city}: витамин D можно синтезировать круглый год.",
    "verdictNever": "{city}: солнце никогда не поднимается достаточно высоко для синтеза витамина D."
  },
  "lt": {
    "verdictRange": "{city}: vitamino D iš saulės galite pasigaminti nuo {startMonth} iki {endMonth}.",
    "verdictAllYear": "{city}: vitamino D iš saulės galite pasigaminti ištisus metus.",
    "verdictNever": "{city}: saulė niekada nepakyla pakankamai aukštai, kad odoje susidarytų vitaminas D."
  }
} as const;
