// Bundles every MCP App widget into one self-contained HTML document each, and
// emits it as a TypeScript module exporting the HTML as a string.
//
// The string module rather than a file on disk is deliberate: the MCP resource
// handler runs in a serverless function, and a static import is something the
// bundler can see and Vercel's output tracing cannot get wrong. The generated
// files are committed for the same reason CI needs them — lint, typecheck and
// tests all run BEFORE the build step that would regenerate them.
import { build } from "esbuild";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { writeFileSync, readFileSync } from "node:fs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const LOCALES = ["en", "es", "fr", "de", "ru", "lt"];

/**
 * Copy a widget shares with the app, lifted from messages/*.json at build time.
 *
 * These are verdicts the user reads in both places — "¡Sal ya! Condiciones
 * excelentes" in the chat has to be the same sentence the app shows for the same
 * state, or the two are describing the same moment differently. Hand-copying 15
 * strings across 6 languages would be stale the first time anyone edits the app.
 *
 * Only the listed keys are pulled: importing a whole locale file would put ~50 KB
 * of unrelated copy inside an iframe bundle.
 */
function emitSharedCopy({ dir, namespace, keys, exportName }) {
  const byLocale = {};
  for (const locale of LOCALES) {
    const messages = JSON.parse(readFileSync(join(root, "messages", `${locale}.json`), "utf8"));
    const ns = messages[namespace] ?? {};
    const picked = {};
    for (const key of keys) {
      if (typeof ns[key] !== "string") throw new Error(`messages/${locale}.json: falta ${namespace}.${key}`);
      picked[key] = ns[key];
    }
    byLocale[locale] = picked;
  }
  const out = `// Generated by scripts/build-widgets.mjs from messages/*.json. Do not edit.
`
    + `export const ${exportName} = ${JSON.stringify(byLocale, null, 2)} as const;
`;
  writeFileSync(join(root, "widgets", dir, "generated-copy.ts"), out, "utf8");
  console.log(`[build-widgets] ${dir}/generated-copy.ts (${keys.length} claves x ${LOCALES.length} idiomas)`);
}

emitSharedCopy({
  dir: "year-strip",
  namespace: "cityPage",
  exportName: "YEAR_COPY",
  keys: ["verdictRange", "verdictAllYear", "verdictNever"],
});

emitSharedCopy({
  dir: "day-curve",
  namespace: "dashboard",
  exportName: "DAY_COPY",
  keys: [
    "nowOptimalTitle", "nowOptimalHint", "nowModerateTitle", "nowModerateHint",
    "nowUpcomingTitle", "nowClosedTitle", "nowClosedHint", "noWindowToday", "noWindowHint",
    "currentUVI", "nowWindow", "nowTimeNeeded", "nowClosesIn", "nowBestHour",
    "cloudDegraded", "cloudDegradedFull",
  ],
});

/** Each widget: source directory under widgets/, and the export name it emits. */
const WIDGETS = [
  { dir: "year-strip", exportName: "YEAR_STRIP_WIDGET_HTML" },
  { dir: "day-curve", exportName: "DAY_CURVE_WIDGET_HTML" },
  { dir: "profile", exportName: "PROFILE_WIDGET_HTML" },
  { dir: "history", exportName: "HISTORY_WIDGET_HTML" },
  { dir: "forecast", exportName: "FORECAST_WIDGET_HTML" },
];

const PAGE_STYLE = "html,body{margin:0;padding:0}"
  + "body{box-sizing:border-box;padding:12px;background:var(--color-background-primary,#fff)}"
  + "*{box-sizing:border-box}#app{width:100%}";

for (const { dir, exportName } of WIDGETS) {
  const result = await build({
    entryPoints: [join(root, "widgets", dir, "entry.ts")],
    bundle: true,
    format: "iife",
    platform: "browser",
    target: "es2022",
    minify: true,
    write: false,
  });

  // `</script` inside the bundle would close the tag early — the one escape a
  // single-file HTML document cannot skip.
  const javascript = result.outputFiles[0].text.replaceAll("</script", "<\\/script");
  const html = `<!doctype html><html><head><meta charset="utf-8">`
    + `<meta name="viewport" content="width=device-width,initial-scale=1">`
    + `<style>${PAGE_STYLE}</style></head>`
    + `<body><div id="app" aria-live="polite"></div><script>${javascript}</script></body></html>`;

  const generated = `// Generated by scripts/build-widgets.mjs. Do not edit.\n`
    + `export const ${exportName} = ${JSON.stringify(html)};\n`;
  writeFileSync(join(root, "widgets", dir, "generated.ts"), generated, "utf8");
  console.log(`[build-widgets] ${dir} (${Buffer.byteLength(html)} bytes)`);
}
