// Bundles every MCP App widget into one self-contained HTML document each, and
// emits it as a TypeScript module exporting the HTML as a string.
//
// The string module rather than a file on disk is deliberate: the MCP resource
// handler runs in a serverless function, and a static import is something the
// bundler can see and Vercel's output tracing cannot get wrong. The generated
// files are committed for the same reason CI needs them — lint, typecheck and
// tests all run BEFORE the build step that would regenerate them.
import { build } from "esbuild";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { writeFileSync } from "node:fs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

/** Each widget: source directory under widgets/, and the export name it emits. */
const WIDGETS = [
  { dir: "year-strip", exportName: "YEAR_STRIP_WIDGET_HTML" },
  { dir: "day-curve", exportName: "DAY_CURVE_WIDGET_HTML" },
  { dir: "profile", exportName: "PROFILE_WIDGET_HTML" },
  { dir: "history", exportName: "HISTORY_WIDGET_HTML" },
];

const PAGE_STYLE = "html,body{margin:0;padding:0}"
  + "body{box-sizing:border-box;padding:12px;background:var(--color-background-primary,#fff)}"
  + "*{box-sizing:border-box}#app{width:100%}";

for (const { dir, exportName } of WIDGETS) {
  const result = await build({
    entryPoints: [join(root, "widgets", dir, "entry.ts")],
    bundle: true,
    format: "iife",
    platform: "browser",
    target: "es2022",
    minify: true,
    write: false,
  });

  // `</script` inside the bundle would close the tag early — the one escape a
  // single-file HTML document cannot skip.
  const javascript = result.outputFiles[0].text.replaceAll("</script", "<\\/script");
  const html = `<!doctype html><html><head><meta charset="utf-8">`
    + `<meta name="viewport" content="width=device-width,initial-scale=1">`
    + `<style>${PAGE_STYLE}</style></head>`
    + `<body><div id="app" aria-live="polite"></div><script>${javascript}</script></body></html>`;

  const generated = `// Generated by scripts/build-widgets.mjs. Do not edit.\n`
    + `export const ${exportName} = ${JSON.stringify(html)};\n`;
  writeFileSync(join(root, "widgets", dir, "generated.ts"), generated, "utf8");
  console.log(`[build-widgets] ${dir} (${Buffer.byteLength(html)} bytes)`);
}
